DATA:
  NUM_IR: 1
  VAL:
    REAL:
        ROOT_DIR: "/share/datasets/sim2real_tactile/real/dataset/"
        SPLIT_FILE: "/share/pengyang/transtouch/split_files/ts_val.txt"
        META_NAME: "meta.pkl"
        DEPTH_NAME: "depthL.png"
        LEFT_NAMES: ("1024_irL_real_360.png",)
        RIGHT_NAMES: ("1024_irR_real_360.png",)
        LABEL_NAME: "labelL.png"
        LEFT_PATTERN_NAME: "1024_irL_real_360.png"
        RIGHT_PATTERN_NAME: "1024_irR_real_360.png"
        HEIGHT: 544
        WIDTH: 960
  TEST:
    REAL:
        ROOT_DIR: "/share/datasets/sim2real_tactile/real/dataset/"
        SPLIT_FILE: "/share/pengyang/transtouch/split_files/ts_test.txt"
        META_NAME: "meta.pkl"
        DEPTH_NAME: "depthL.png"
        LEFT_NAMES: ("1024_irL_real_360.png",)
        RIGHT_NAMES: ("1024_irR_real_360.png",)
        LABEL_NAME: "labelL.png"
        LEFT_PATTERN_NAME: "1024_irL_real_360.png"
        RIGHT_PATTERN_NAME: "1024_irR_real_360.png"
        HEIGHT: 544
        WIDTH: 960
  TUNE:
    REAL:
      ROOT_DIR: "/share/datasets/sim2real_tactile/touch/"
      SPLIT_FILE: "/share/pengyang/transtouch/split_files/ts_tune.txt"
      META_NAME: "meta.pkl"
      LEFT_NAMES: ("1024_irL_real_360.png",)
      RIGHT_NAMES: ("1024_irR_real_360.png",)
      LEFT_PATTERN_NAME: "1024_irL_real_360.png"
      RIGHT_PATTERN_NAME: "1024_irR_real_360.png"
      HEIGHT: 544
      WIDTH: 960
    SIM:
      ROOT_DIR: "/share/datasets/sim2real_tactile/sapien0923/data"
      SPLIT_FILE: "/share/pengyang/transtouch/split_files/sapien0923_train.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAMES: ("0128_ir00L_kuafu_half.png",)
      RIGHT_NAMES: ("0128_ir00R_kuafu_half.png",)
      LEFT_PATTERN_NAME: "0128_ir00L_kuafu_half.png"
      RIGHT_PATTERN_NAME: "0128_ir00R_kuafu_half.png"

MODEL_TYPE: "PSMNetEdgeNormal"
PSMNetEdgeNormal:
  DILATION: 3
  EDGE_WEIGHT: 15.0
  EPSILON: 1.0
  GRAD_THRESHOLD: 10.0
  MAX_DISP: 96
  MIN_DISP: 12
  NUM_DISP: 192
  SET_ZERO: False
  USE_OFF: False
  USE_VOLUME: False

OPTIMIZER:
  TYPE: "Adam"
  LR: 2e-5
LR_SCHEDULER:
  TYPE: 'StepLR'
  StepLR:
    step_size: 2000
    gamma: 0.2
TRAIN:
  BATCH_SIZE: 2
  NUM_WORKERS: 16
  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 500
  MAX_TO_KEEP: 120
  MAX_ITER: 60000
VAL:
  BATCH_SIZE: 4
  NUM_WORKERS: 16
  PERIOD: 20
  LOG_PERIOD: 100
LOSS:
  SIM_DISP:
    WEIGHT: 0.0
  REAL_REPROJ:
    WEIGHT: 0.0
  TUNE_PSEUDO:
    WEIGHT: 100.0

TEST:
  NUM_WORKERS: 0
  MAX_DISP: 192
  WEIGHT: ""

TUNE:
  MODE: "Entropy"
  BATCH_SIZE: 1
  NUM_WORKERS: 0
  MAX_DISP: 192
  MAX_TO_KEEP: 100
  MAX_ITER: 300
  LOG_PERIOD: 20
  CHECKPOINT_PERIOD: 20
  WEIGHT: ""
  NUM_TOUCH: 5
  TOUCH_SIZE: 11
  CONF_RANGE: 1
  PSEUDO_THRESHOLD: 0.9999
  GAUSSIAN_KERNEL: 15
  GAUSSIAN_SIGMA: 12.0
  LR: 1e-6
  LOSS:
    PRED1: 0.5
    PRED2: 0.7
    PRED3: 1.0
  USE_SIM: true
  TACTILE_PATH: "tune_4"
DATA_AUG:
  SIM_IR: true
RESUME_STRICT: false
USE_PSEUDO_LOSS: true
